-- SALES & REVENUE ANALYSIS--
-- 1. What is the total revenue generated by BlinkIt?
SELECT sum(order_total) AS 'Revenue' FROM blinkit_orders
WHERE delivery_status='On Time';

-- OR--

SELECT SUM(oi.quantity * oi.unit_price) AS revenue
FROM blinkit_order_items oi
JOIN blinkit_orders o
  ON oi.order_id = o.order_id
WHERE o.delivery_status = 'On Time';

-- 2. Monthly Revenue Trend--
SELECT YEAR(order_date) AS year,
MONTH(order_date) AS month,
SUM(order_total) AS Revenue
FROM blinkit_orders bo
WHERE delivery_status='On Time'
GROUP BY YEAR(order_date), MONTH(order_date)
ORDER BY year,month;

-- 3. Average Order Value--
SELECT AVG(order_total) AS average_order_value
FROM blinkit_orders
WHERE delivery_status = 'On Time';

-- OR--

WITH order_revenue AS(
SELECT oi.order_id, sum(oi.quantity*oi.unit_price) AS total_revenue 
FROM blinkit_order_items oi
JOIN blinkit_orders o ON o.order_id=oi.order_id
WHERE o.delivery_status='On Time'
GROUP BY oi.order_id
)
SELECT ROUND(AVG(total_revenue),2) AS average_reveue 
FROM order_revenue;

-- 4. Day of the week with Highest Revenue--
SELECT DAYNAME(order_date) AS day_of_the_week, sum(order_total) AS total_revenue 
FROM blinkit_orders
WHERE delivery_status ='On Time' OR 'Slightly Delayed'
GROUP BY DAYNAME(order_date)
ORDER BY total_revenue DESC
LIMIT 1;

-- Order Analysis--
-- 5. How many orders are Delivered On Time?--

SELECT 
    SUM(CASE WHEN delivery_status = 'On Time' THEN 1 ELSE 0 END) AS on_time_orders,
    SUM(CASE WHEN delivery_status = 'Slightly Delayed' THEN 1 ELSE 0 END) AS delayed_orders
FROM blinkit_orders;


-- 6. Average number of items per order--
SELECT ROUND(AVG(total_items), 2) AS avg_items_per_order
FROM (
    SELECT 
        order_id,
        SUM(quantity) AS total_items
    FROM blinkit_order_items
    GROUP BY order_id
) t;

-- 7.  Orders with order value above average
-- (using price × quantity, as you prefer)
-- Step 1: Compute total revenue 
-- Step 2: Compare with overall average

WITH order_revenue AS (
SELECT oi.order_id,
SUM(oi.quantity*oi.unit_price) AS order_value
FROM blinkit_order_items oi
GROUP BY oi.order_id
), 
avg_value AS (
    SELECT AVG(order_value) AS avg_order_value
    FROM order_revenue
)
SELECT 
    o.order_id,
    o.order_value
FROM order_revenue o, avg_value a
WHERE o.order_value > a.avg_order_value;

-- 8.  Distribution of order sizes (Small / Medium / Large)--
-- Small: < 1000
-- Medium: 1000 – 3000
-- Large: > 3000

WITH order_revenue AS (
    SELECT 
        oi.order_id,
        SUM(oi.quantity * oi.unit_price) AS total_orders
    FROM blinkit_order_items oi
    GROUP BY oi.order_id
)
SELECT 
    CASE 
        WHEN total_orders < 1000 THEN 'Small'
        WHEN total_orders BETWEEN 1000 AND 3000 THEN 'Medium'
        ELSE 'Large'
    END AS order_size,
    COUNT(*) AS number_of_orders
FROM order_revenue
GROUP BY order_size;

-- 9. Which stores handle the highest number of orders?--
SELECT store_id,COUNT(order_id) AS total_orders
FROM blinkit_orders
GROUP BY store_id
ORDER BY total_orders DESC;

-- CUSTOMER ANALYSIS
-- 10. Who are the top 10 customers by total spending?
SELECT o.order_id, c.customer_id FROM blinkit_orders o
JOIN blinkit_customers c ON c.customer_id=o.customer_id
GROUP BY c.customer_name,c.customer_id
ORDER BY o.order_total DESC;


-- 11. Find the number of Repeat Customers
SELECT COUNT(*) AS 'Repeat Customers'
FROM(
SELECT customer_id FROM blinkit_orders
WHERE delivery_status='ON TIME'
GROUP BY customer_id
HAVING COUNT(customer_id)>1
)rc;

-- 12. Find the average number of orders per customer--
SELECT AVG(total_order_per_customer) AS avg_order_per_customer
FROM(
SELECT bo.customer_id,bo.customer_name, COUNT(bo.customer_id) AS total_order_per_customer FROM blinkit_customers bo
JOIN blinkit_customers bc ON bc.customer_id=bo.customer_id
GROUP BY bo.customer_id,bo.customer_name
) a;

-- 13. Find the customer-wise Revenue contribution
SELECT bc.customer_id,bc.customer_name,(bot.quantity*bot.unit_price) AS Revenue FROM blinkit_customers bc
JOIN blinkit_orders bo ON bo.customer_id=bc.customer_id
JOIN blinkit_order_items bot ON bot.order_id=bo.order_id
GROUP BY bc.customer_id,bc.customer_name,Revenue
ORDER BY Revenue DESC;

-- 14. Find the area wise customer concentration--
SELECT area, COUNT(DISTINCT customer_id) AS total_customers FROM blinkit_customers
GROUP BY area
ORDER BY  total_customers DESC;

-- 15. Find the High value customers who spend more than averge
WITH customer_revenue AS (
SELECT bc.customer_id,bc.customer_name, SUM(bot.quantity*bot.unit_price) AS Total_Revenue FROM blinkit_customers bc
JOIN blinkit_orders bo ON bo.customer_id=bc.customer_id
JOIN blinkit_order_items bot ON bot.order_id=bo.order_id
GROUP BY bc.customer_id,bc.customer_name
ORDER BY Total_Revenue DESC),

avg_spend AS (
SELECT AVG(Total_Revenue) AS avg_revenue
    FROM customer_revenue
)
SELECT cr.customer_id,
    cr.customer_name,
    cr.Total_Revenue
FROM customer_revenue cr, avg_spend a
WHERE cr.Total_Revenue > a.avg_revenue;

